### PR TITLE
Add ability to use item specific elClass on tiles

### PR DESCRIPTION
**Pull request by bsstoner**
@moollaza wanted this functionality. I can't remember which IA was going to use it, but they wanted to specify a top level class for certain items that would let control the entire tile's state. Maybe Flights?

@sdougbrown would like your thoughts on this.

I'd also love to rename `elClass` to something more intelligible... but that's probably outside the scope of this.

### CODE REVIEW

**Comment by moollaza** [comment]
@bsstoner yup this will be used in the new Flights IA so we can set the status for each tile based on the status of the flight (landed, on time, delayed, cancelled, etc) so we can style the tile appropriately

**Comment by sdougbrown** [comment]
I think that `tileClass` would make a bit more sense than `elClass` in this case?  `elClass` is supposed to be a container object for different element classNames, and using it in two different ways can be a bit confusing.  I feel like I'd like to normalize this internally so we can just have `{{tileClass}}` in the templates instead of repeating this if statement everywhere, but this would work for now...

**Comment by bsstoner** [comment]
Cool, thanks for the thoughts. We can leave `elClass` for now, I think a rename is beyond the scope of this PR, but worth considering at some point maybe.

Do you think this PR is okay otherwise? Conceptually letting people specify different outer classes at an item level?

**Comment by sdougbrown** [comment]
Yeah overall this is fine for now. :+1:

**Pull request merged**
