### PR TITLE
Remove colon from Record template

### PR DESCRIPTION
**Pull request by moollaza**
As per @abeyang's request

/cc @jagtalon @bsstoner

### CODE REVIEW

**Comment by jagtalon** [comment]
@moollaza thanks! Checking it.

**Comment by jagtalon** [comment]
Looks good to everyone?

screen shot 2015-09-28 at 4 19 11 pm
screen shot 2015-09-28 at 4 19 18 pm
screen shot 2015-09-28 at 4 19 22 pm

**Comment by bsstoner** [comment]
:+1:

**Comment by abeyang** [comment]
:+1:

**Comment by jagtalon** [comment]
@moollaza :+1:

**Pull request merged**
